#ddev-generated
ahoyapi: v2
commands:
  build:
    usage: 'Tidy up README.md'
    cmd: |
      prettier /var/www/html/README.md --write --config=/var/www/html/.ddev/readme/.prettierrc
      markdown-toc -i /var/www/html/README.md

  watch:
    usage: 'Watch README.md for changes'
    cmd: |
      node /var/www/html/.ddev/readme/watch.js
