#ddev-generated
hooks:
  post-import-db:
    - exec: /var/www/html/.ddev/pimp-my-shell/hooks/post-import-db.sh
webimage_extra_packages:
  - bash-completion
  - boxes
  - bsdmainutils
  - build-essential
  - kitty-terminfo
  - libarchive-tools
  - lua5.4
  - pv
web_environment:
  - COLORTERM=${COLORTERM}
