name: update
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:

  updates:
    name: Check for updates
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      updates: ${{ steps.check-updates.outputs.updates }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install ddev/ddev/ddev >/dev/null
      - uses: actions/checkout@v4
      - name: 'Run updates'
        run: |
          ./update.sh
      - name: Check if something was updated
        id: check-updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git diff > /tmp/updates.patch
            echo "updates=true" >> "$GITHUB_OUTPUT"
          else
            echo "updates=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/upload-artifact@v4
        if: steps.check-updates.outputs.updates == 'true'
        with:
          name: patch
          path: /tmp/updates.patch
          if-no-files-found: error

  tests:
    name: Test the updates
    runs-on: ubuntu-latest
    needs: updates
    if: needs.updates.outputs.updates == 'true'
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: patch
          path: /tmp
      - run: git apply /tmp/updates.patch
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          disable_checkout_action: true

  commitpush:
    name: Commit and push the updates
    runs-on: ubuntu-latest
    needs: tests
    if: needs.updates.outputs.updates == 'true'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: patch
          path: /tmp
      - run: git apply /tmp/updates.patch
      - name: 'Commit changes'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "build: automatic update.sh updates (GA)"
          git pull --rebase
          git push

  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
