name: update
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:

  main:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    name: Push updates
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      actions: write
      contents: write
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install ddev/ddev/ddev >/dev/null
      - uses: actions/checkout@v4
      - name: 'Run updates'
        run: |
          ./update.sh
      - name: Check if something was updated
        id: check-updates
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "updates=true" >> "$GITHUB_OUTPUT"
          else
            echo "updates=false" >> "$GITHUB_OUTPUT"
          fi

      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
          disable_checkout_action: true

      - name: 'Commit changes'
        if: steps.check-updates.outputs.updates == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "build: automatic update.sh updates (GA)"
          git push

  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
