name: update
on:
  schedule:
    - cron: "12 0 * * *"
  workflow_dispatch:
jobs:

  main:
    name: Push updates
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      actions: write
      contents: write
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install ddev/ddev/ddev >/dev/null
      - uses: actions/checkout@v4
      - name: 'Run updates and commit'
        run: |
          ./update.sh
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "feat: update.sh updates (GA)"
            git push
            gh workflow run tests
          fi

  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
